package io.cui.test.generator.impl;

import io.cui.test.generator.TypedGenerator;
import io.cui.test.generator.internal.net.java.quickcheck.generator.PrimitiveGenerators;
import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;

/**
 * This Class is used to generate a Float Object value which is generated by next() method.
 *
 * @author i001456
 */
@AllArgsConstructor
@NoArgsConstructor
public class FloatObjectGenerator implements TypedGenerator<Float> {

    private float low = Float.MIN_VALUE;
    private float high = Float.MAX_VALUE;

    @Override
    public Float next() {
        return PrimitiveGenerators.doubles(low, high).next().floatValue();
    }

    @Override
    public Class<Float> getType() {
        return Float.class;
    }

}
