package io.cui.test.generator.impl;

import static io.cui.test.generator.Generators.integers;

import io.cui.test.generator.TypedGenerator;

/**
 * This Class is used to generate a {@link Number} objects which is generated by next() method.
 *
 * @author i001456
 */
public class NumberGenerator implements TypedGenerator<Number> {

    @Override
    public Number next() {
        return integers().next();
    }

    @Override
    public Class<Number> getType() {
        return Number.class;
    }

}
