package io.cui.test.generator.impl;

import io.cui.test.generator.TypedGenerator;
import io.cui.test.generator.internal.net.java.quickcheck.generator.PrimitiveGenerators;

/**
 * This Class is used to generate a Short Object value which is generated by next() method.
 *
 */
public class ShortObjectGenerator implements TypedGenerator<Short> {

    @Override
    public Short next() {
        return PrimitiveGenerators.integers(-32768, 32767).next().shortValue();
    }

    @Override
    public Class<Short> getType() {
        return Short.class;
    }

}
