= cui-test-generator

== Status

image:https://github.com/cuioss/cui-test-generator/actions/workflows/maven.yml/badge.svg[Java CI with Maven,link=https://github.com/cuioss/cui-test-generator/actions/workflows/maven.yml]
image:http://img.shields.io/:license-apache-blue.svg[License,link=http://www.apache.org/licenses/LICENSE-2.0.html]
image:https://maven-badges.herokuapp.com/maven-central/io.github.cuioss/cui-test-generator/badge.svg[Maven Central,link=https://maven-badges.herokuapp.com/maven-central/io.github.cuioss.test/cui-test-generator]

https://sonarcloud.io/summary/new_code?id=cuioss_cui-test-generator[image:https://sonarcloud.io/api/project_badges/measure?project=cuioss_cui-test-generator&metric=alert_status[Quality
Gate Status]]
image:https://sonarcloud.io/api/project_badges/measure?project=cuioss_cui-test-generator&metric=ncloc[Lines of Code,link=https://sonarcloud.io/summary/new_code?id=cuioss_cui-test-generator]
image:https://sonarcloud.io/api/project_badges/measure?project=cuioss_cui-test-generator&metric=coverage[Coverage,link=https://sonarcloud.io/summary/new_code?id=cuioss_cui-test-generator]

https://cuioss.github.io/cui-test-generator/index.html[Generated Documentation on github-pages]

== What is it?

Using the generators help creating variations of test-data. On the one hand it produces a large number of different values. On the other hand it makes error cases reproducible see `io.cui.test.generator.junit.EnableGeneratorController` and `io.cui.test.generator.junit.GeneratorSeed` for details.

=== Maven Coordinates

[source,xml]
----
    <dependency>
        <groupId>io.github.cuioss.test</groupId>
        <name>cui-test-generator</name>
    </dependency>
----

=== Generators
Using the generators help creating variations of test-data. On the one hand it produces a large number of different values. On the other hand it makes error cases reproducible see `io.cui.test.generator.junit.EnableGeneratorController` and `io.cui.test.generator.junit.GeneratorSeed` for details.

=== Provided Features
The generators defined within this packages are the base for the cui-value-object test framework. In essence, it is a variant of QuickCheck. In the current implementation it actually uses code derived from QuickCheck, thanks guys, but mostly the generator part.
This code is isolated in `io.cui.test.generator.internal.net.java.quickcheck` and will be replaced in the future.

Therefore: Do not use any of that code at all! Central elements are:

* `io.cui.test.generator.TypedGenerator`: Is the core type. Instances of it are used for generating arbitrary instances of any value-object. Compared to `io.cui.test.generator.internal.net.java.quickcheck.Generator` it provides an additional method providing runtime information on the type being generated: `io.cui.test.generator.TypedGenerator.getType()`.
* `io.cui.test.generator.Generators`: Factory methods for accessing io.cui.test.generator.TypedGenerator for many java-lang types.
* `io.cui.test.generator.domain`: Provides some domain specific io.cui.test.generator.TypedGenerator

=== Usage

The usage is straight forward `TypedGenerator#next()` always returns a random object that can be used for testing. See section 'Generators' on samples for concrete generators.

=== TypedGenerator

`io.cui.test.generator.TypedGenerator`

Central interface for a concrete generator instance. `TypedGenerator#next()` provides a random instance, `TypedGenerator#getType()` provides the types.
Sample implementation: 

[source,java]
----
public class ZoneOffsetGenerator implements TypedGenerator<ZoneOffset> {

    private static final TypedGenerator<ZoneId> ZONE_IDS_GEN =
        Generators.fixedValues(ZoneId.class, getAvailableZoneIds().stream().map(ZoneId::of).collect(toList()));

    @Override
    public java.time.ZoneOffset next() {
        return LocalDateTime.now().atZone(ZONE_IDS_GEN.next()).getOffset();
    }

    @Override
    public Class<ZoneOffset> getType() {
        return ZoneOffset.class;
    }

}
----

=== Generators

`io.cui.test.generator.Generators`

Central factory for `TypedGenerator` for most java-built-in types and wrappers for `fixedValue` and `enumValue` variants

[source,java]
----
 assertNotNull(Generators.strings().next());
 assertNotNull(Generators.letterStrings().next());
 assertFalse(isEmpty(Generators.nonEmptyStrings().next())); 
 assertFalse(isEmpty(Generators.letterStrings(1, 2).next()));
 
 assertNotNull(Generators.booleans().next());
 assertNotNull(Generators.localTimes().next());
 assertNotNull(Generators.fixedValues(String.class, "http://de.icw-global.com", "https://www.heise.de", "http://getbootstrap.com").next());
 
 assertEquals(Temporal.class, Generators.temporals().getType());
 assertNotNull(Generators.enumValues(PropertyMemberInfo.class).next());
 assertEquals(PropertyMemberInfo.class, Generators.enumValues(PropertyMemberInfo.class).getType());
----

=== CollectionGenerator

`io.cui.test.generator.impl.CollectionGenerator<T>`

Wraps a given `TypedGenerator` and provides  additional methods for creating `Lists` and `Sets`

[source,java]
----
 CollectionGenerator<String> generator = new CollectionGenerator<>(Generators.nonEmptyStrings());
 assertNotNull(generator.list());
 assertNotNull(generator.set());
----

=== EnableGeneratorController

`io.cui.test.generator.junit.EnableGeneratorController`

This annotation is meant to be set on a junit 5 test-case. It controls the generator subsystem and, in case of test-failures, provides information, that can be used for repeating the failed tests with a fixed seed for the generators, see `io.cui.test.generator.junit.GeneratorSeed` for details.
This fixed seed results in the generators reproducing the exact same test-data.

Sample output:
[source,text]
----
GeneratorController seed was 4711L.
Use a fixed seed by applying @GeneratorSeed(4711L) for the method/class,
or by using the system property '-Dio.cui.test.generator.seed=4711'
----

=== GeneratorSeed

`io.cui.test.generator.junit.GeneratorSeed`

This annotation is to be used in the context of EnableGeneratorController. It explicitly sets the seed for the generators.

Usage:

[source,java]
----
@EnableGeneratorController
@GeneratorSeed(5L)
class GeneratorControllerExtensionTest {

    @Test
    @GeneratorSeed(11L)
    void shouldReadFromMethod() {
        assertEquals(11L, RandomConfiguration.getLastSeed());
    }

    @Test
    void shouldReadFromType() {
        assertEquals(5L, RandomConfiguration.getLastSeed());
    }
----

